export default [
	{
		id: 1,
		name: "Ada Wong",
		game: "Resident Evil",
		img: "ada.jpg",
		gender: "female",
		video: "ada.mp4",
		volume: 0.6,
	},
	{
		id: 2,
		name: "Jill Valentine",
		game: "Resident Evil",
		gender: "female",
		img: "jill.jpg",
		video: "jill.mp4",
		volume: 0.4,
	},
	{
		id: 3,
		name: "Clementine",
		game: "The Walking Dead",
		gender: "female",
		img: "clementine.jpg",
		video: "clementine.mp4",
		volume: 0.4,
	},
	{
		id: 4,
		name: "Bela Dimitrescu",
		game: "Resident Evil Village",
		gender: "female",
		img: "bella.jpg",
		video: "bella-dimitrescu.mp4",
		volume: 0.8,
	},
	{
		id: 5,
		name: "Ciri",
		game: "The Witcher III",
		gender: "female",
		img: "ciri.jpg",
		video: "ciri.mp4",
		volume: 1,
	},
	{
		id: 6,
		name: "Sam",
		game: "Until Dawn",
		gender: "female",
		img: "sam.jpg",
		video: "sam.mp4",
		volume: 1,
	},
	{
		id: 7,
		name: "Lara Croft",
		game: "Tomb Raider",
		gender: "female",
		img: "lara-croft.jpg",
	},
	{
		id: 8,
		name: "Ashley Graham",
		game: "Resident Evil",
		gender: "female",
		img: "ashley-graham.jpg",
		video: "ashley-graham.mp4",
		volume: 0.4,
	},
	{
		id: 9,
		name: "Ellie Williams",
		game: "The Last of Us",
		gender: "female",
		img: "ellie-williams.jpg",
		video: "ellie-williams.mp4",
		volume: 0.4,
	},
	{
		id: 10,
		name: "Miranda",
		game: "Resident Evil",
		gender: "female",
		img: "miranda.jpg",
	},
	{
		id: 11,
		name: "Leon Kennedy",
		game: "Resident Evil",
		gender: "male",
		img: "leon.jpg",
		video: "leon.mp4",
		volume: 0.6,
	},
	{
		id: 12,
		name: "Albert Wesker",
		game: "Resident Evil",
		gender: "male",
		img: "albert.jpg",
	},
	{
		id: 13,
		name: "Carlos Oliveira",
		game: "Resident Evil 3",
		gender: "male",
		img: "carlos.jpg",
		video: "carlos.mp4",
		volume: 0.4,
	},
	{
		id: 14,
		name: "Josh Washington",
		game: "Until Dawn",
		gender: "male",
		img: "josh.jpg",
	},
	{
		id: 15,
		name: "Geralt of Rivia",
		game: "The Witcher",
		gender: "male",
		img: "geralt.jpg",
	},
	{
		id: 16,
		name: "Joel Miller",
		game: "The Last of Us",
		gender: "male",
		img: "joel.jpg",
	},
	{
		id: 17,
		name: "Luis Sera",
		game: "Resident Evil 4",
		gender: "male",
		img: "luis.jpg",
		video: "luis.mp4",
		volume: 1,
	},
	{
		id: 18,
		name: "Connor",
		game: "Detroit: Become Human",
		gender: "male",
		img: "connor.jpg",
		video: "connor.mp4",
		volume: 1,
	},
	{
		id: 19,
		name: "Arthur Morgan",
		game: "Red Dead Redemption 2",
		gender: "male",
		img: "arthur.jpg",
	},
	{
		id: 20,
		name: "Mike Munroe",
		game: "Until Dawn",
		gender: "male",
		img: "mike.jpg",
		video: "mike.mp4",
		volume: 0.4,
	},
];
